# Generated by Django 4.2.6 on 2023-10-21 07:54

import app.app
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('Brand_Agency', models.CharField(max_length=100)),
                ('Industry', models.CharField(max_length=100)),
                ('Collaboration_Type', models.CharField(max_length=25)),
                ('file', app.app.ContentTypeRestrictedFileField(upload_to='pdf')),
                ('Date', models.DateTimeField(default=datetime.datetime(2023, 10, 21, 13, 24, 27, 824255))),
            ],
        ),
    ]
