# Generated by Django 4.2.6 on 2023-10-21 14:06

import app.app
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('Brand_Agency', models.CharField(max_length=35)),
                ('Industry', models.CharField(max_length=30)),
                ('Kind_Sponcer', models.CharField(max_length=30)),
                ('Sponcer_Type', models.CharField(max_length=30)),
                ('file', app.app.ContentTypeRestrictedFileField(upload_to='pdf')),
                ('Date', models.DateTimeField(default=datetime.datetime(2023, 10, 21, 19, 36, 6, 813894))),
            ],
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 21, 19, 36, 6, 813894)),
        ),
    ]
