# Generated by Django 4.2.6 on 2023-10-25 07:56

import app.app
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contactdata_alter_collaboration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=400)),
                ('file', app.app.ContentTypeRestrictedFileField(upload_to='pdf')),
                ('Date', models.DateTimeField(default=datetime.datetime(2023, 10, 25, 13, 26, 5, 780157))),
            ],
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 13, 26, 5, 779158)),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 13, 26, 5, 780157)),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 13, 26, 5, 779158)),
        ),
    ]
