# Generated by Django 4.2.6 on 2023-10-25 10:48

import app.app
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ideas_alter_collaboration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=50)),
                ('LastName', models.CharField(blank=True, max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=10)),
                ('Experience', models.CharField(max_length=20)),
                ('file', app.app.ContentTypeRestrictedFileField(upload_to='pdf')),
                ('Date', models.DateTimeField(default=datetime.datetime(2023, 10, 25, 16, 18, 25, 955922))),
            ],
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 16, 18, 25, 955922)),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 16, 18, 25, 955922)),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 16, 18, 25, 955922)),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 16, 18, 25, 955922)),
        ),
    ]
