# Generated by Django 4.2.6 on 2023-11-03 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_application_date_alter_collaboration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogposts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2023, 11, 3, 13, 13, 46, 102977))),
                ('image', models.ImageField(upload_to='blog_images')),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 13, 13, 46, 102977)),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 13, 13, 46, 102977)),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 13, 13, 46, 102977)),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 13, 13, 46, 102977)),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 13, 13, 46, 102977)),
        ),
    ]
