# Generated by Django 4.2.6 on 2023-11-06 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_careers_career_alter_application_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobsummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('work_exp', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('working_time', models.CharField(max_length=50)),
                ('deadline', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 17, 34, 10, 939327)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 17, 34, 10, 940332)),
        ),
        migrations.AlterField(
            model_name='category',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 17, 34, 10, 940332)),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 17, 34, 10, 938130)),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 17, 34, 10, 939327)),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 17, 34, 10, 939327)),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 17, 34, 10, 938130)),
        ),
    ]
