# Generated by Django 4.2.6 on 2023-11-06 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_application_date_alter_blogpost_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 18, 42, 9, 758283)),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 18, 42, 9, 759307)),
        ),
        migrations.AlterField(
            model_name='category',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 18, 42, 9, 758283)),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 18, 42, 9, 756131)),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 18, 42, 9, 757232)),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 18, 42, 9, 757232)),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 18, 42, 9, 756131)),
        ),
    ]
